## NUMPY



In [23]:
import numpy as np

In [24]:
import numpy as np

## Array yaratmak


Python listlerine benzeyen, aynı tipten çok sayıda elemanı içeren, hızlı işlem yapılmasını sağlayan kavramlardır.

Her matrix bir array olur, her array bir matrix olmaz. Array tek boyutlu olabilir aşağıdaki gibi ama matris olmaz:

2 boyutlu arraylere matris diyoruz. Tek boyutlu matris olmaz

In [27]:
x= np.array([1,2,3,4])

In [28]:
x

array([1, 2, 3, 4])

In [29]:
type(x)

numpy.ndarray

In [30]:
m= np.array(["a","b","c"])

In [31]:
m

array(['a', 'b', 'c'], dtype='<U1')

In [32]:
n= np.array([1,2,3,"a"])

In [33]:
# eğer arrayin içinde bir tane bile karakter varsa; elemanlar, arrayın içinde string tipinde tutulur.
n

array(['1', '2', '3', 'a'], dtype='<U11')

In [34]:
# 1 tane float olduğu için dğer integerlar da floata dönüştü
z= np.array([1,2,3,3.5])

In [35]:
z

array([1. , 2. , 3. , 3.5])

## Array data tipini belirleme

In [37]:
x=np.array([1,2,3.4])

In [38]:
x

array([1. , 2. , 3.4])

In [39]:
x=np.array([1,2,3.6], dtype="int32")   #arrayin tipini integer yapma

In [131]:
x

array([1, 2, 3])

In [133]:
y=np.array([1,2,3.4], dtype="str") #arrayin tipini str yapma

In [135]:
y

array(['1', '2', '3.4'], dtype='<U3')

In [43]:
y=np.array([1,2,"a"], dtype="int32")  #str olduğu için integer hale getiremeyiz.

ValueError: invalid literal for int() with base 10: 'a'

## Elemanları 0 olan array

In [137]:
c= np.zeros(10)

c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [702]:
#3 satır(row) ve 5 sütun(kolon)
a=np.zeros((3,5)) #zeros vs derken iki boyutluysa tek parantez yetmiyo

a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [141]:
# 2 boyutlu 3x5 lik array = matris
x= np.zeros([3,5])
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [712]:
# 3 boyutlu
# 4 tane 5x7 lik array kur  #tensör
y= np.zeros((4,5,7))
y

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [714]:
y.dtype

dtype('float64')

## array bilgilerine erişme

In [145]:
c.shape

(10,)

In [716]:
c.dtype

dtype('int32')

In [147]:
a.shape

(3, 5)

In [149]:
x.shape

(3, 5)

In [151]:
y.shape

(4, 5, 7)

In [157]:
c.ndim #kaç boyutlu

1

In [155]:
a.ndim

2

In [159]:
#boyut
x.ndim

2

In [161]:
#boyut
y.ndim

3

In [163]:
#array içindeki eleman (3*5)
x.size

15

In [165]:
# 4*5*7
y.size


140

### np.full

In [209]:
# 3x5 lik elemanları 7 olan array
np.full((3,5),7) #full içini doldur anlamında düşünülebilir, virgülden sonrası içini doldurduğun şey

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [171]:
np.full((3,5),7, dtype="int32")

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [173]:
np.full((3,5),"m")

array([['m', 'm', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm', 'm']], dtype='<U1')

In [201]:
a=np.full((5,4,6), "zülal")

a

array([[['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal'],
        ['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal'],
        ['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal'],
        ['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal']],

       [['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal'],
        ['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal'],
        ['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal'],
        ['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal']],

       [['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal'],
        ['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal'],
        ['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal'],
        ['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal']],

       [['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal'],
        ['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal'],
        ['zülal', 'zülal', 'zülal', 'zülal', 'zülal', 'zülal'],
        ['zülal', 'zülal', 'zülal'

In [203]:
a.size

120

In [205]:
a.ndim

3

In [207]:
a.shape

(5, 4, 6)

### ardışık sayılardan array

In [211]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [213]:
np.arange(0,14,2) # 2 atlamalı şekilde 14'e kadar array oluşturdu

array([ 0,  2,  4,  6,  8, 10, 12])

In [215]:
np.arange(54,100,3)

array([54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## aralığı eşit uzaklıkta bölerek array oluşturma

verilen başlangıç ve bitiş noktasına göre, başlangıç ve bitiş noktası da dahil, aradaki sayıları eşit uzaklıkta olacak şekilde yazarak oluşturur. (linspace)

In [217]:
#default olarak aradaki mesafeyi 50 nokta olacak şekilde yazar
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [225]:
np.linspace(50,100,5)

array([ 50. ,  62.5,  75. ,  87.5, 100. ])

In [231]:
np.linspace(1,2).ndim

1

In [233]:
#num=3 ile 1-2 arasındaki mesafeyi kendileri dahil 3'e bölüyor.
np.linspace(1,2,num=3)

array([1. , 1.5, 2. ])

In [235]:
np.linspace(1.5,3, num=3)

array([1.5 , 2.25, 3.  ])

In [647]:
np.linspace(1,3,3)

array([1., 2., 3.])

In [657]:
np.linspace(1,3,3, endpoint=False) #3'ü dahil etmiyor 

array([1.        , 1.66666667, 2.33333333])

## Normal Dağılıma Uygun değerler ile array oluşturma

np.random.normal(mean, std, array shape)

In [239]:
np.random.normal(0,1, (3,5)) #0 ortalamalı, standart sapması 1 olacak şekilde (3x5)lik
#bir normal dağılıma uygun array oluşturduk

array([[ 2.18526708,  0.5923806 , -0.32723348,  2.14595012, -0.52063378],
       [-1.00279057, -1.95907227, -0.30673831, -1.60344788, -0.47291829],
       [-0.83832892, -1.66761137, -1.92228548,  0.71335295, -1.44114144]])

In [241]:
np.random.normal(0,100, (3,5))

array([[-153.48495238,   33.4455789 ,  -86.7041896 ,  -51.37273518,
          30.15291667],
       [ -43.98401207,  -41.58827614,   -6.62943071,  -11.44725195,
        -102.64855722],
       [-174.28315492,   17.92948766,  -61.54911674,   25.16121917,
         -22.38937237]])

## Random olarak

In [257]:
# np.random.randint(low,high) #1 min 15 de max sayısı oldu literally random - random integers: randint - low olan küçük eşit yani 1 olcak diye bişi yok
# 15 dahil değil

np.random.randint(1,15,(3,5))

array([[ 8,  8,  8,  9,  6],
       [13,  9,  4,  3,  8],
       [13,  1,  2,  7,  6]])

In [247]:

np.random.randint(5,15,(3,5))

array([[13, 14,  9, 13,  8],
       [ 9, 12,  8, 12, 10],
       [ 6, 11,  5,  8,  9]])

In [263]:
np.random.randint(13,100,(5,5)) #sadece 100 kesin yok yani

array([[54, 96, 44, 77, 29],
       [98, 89, 96, 34, 30],
       [36, 49, 75, 64, 60],
       [63, 81, 52, 57, 96],
       [50, 79, 76, 24, 41]])

In [665]:
val=np.random.randint(1,11)
val

7

Cohort Sorusu - tam anlamadım dursun

In [683]:
d={}
for _ in range(20000):
    val=np.random.randint(1,11)
if val not in d:
    d[val]=1
else:
    d[val]+=1
d

{8: 1}

In [690]:
np.array([3,5,9])*3 #arrayse çarpıyor

array([ 9, 15, 27])

In [692]:
[3,5,9]*3 #listse concatenate

[3, 5, 9, 3, 5, 9, 3, 5, 9]

In [265]:
# birim array yaratma (köşegenleri 1 olan diğer elemanları 0 olan array)
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [267]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [269]:
np.eye(5,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [273]:
np.eye(5) #ttek sayı yazarsan kare geliyo direkt

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Array Matematiksel İşlemler

In [275]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [277]:
x

array([1, 2, 3])

In [279]:
x*y

array([ 4, 10, 18])

In [281]:
x+y

array([5, 7, 9])

In [283]:
print(x+y)

[5 7 9]


In [285]:
x= np.array([1,2,3])
y= np.array([4,5,6,8])

x*y  #(arraylar birbirine denk olmadığı için hata aldık)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [287]:
#note: listede toplama işlemi tanımlı değil
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [289]:
a= np.array([    [1,2,3],[4,5,6]      ])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [291]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [293]:
a.ndim

2

In [295]:
a.shape

(2, 3)

In [297]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [299]:
a+a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [301]:
a/a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [303]:
a*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [305]:
a+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [307]:
#her bir değerin karekökünü aldı
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [309]:
#matris gibi çarpım yapar. (dot) (shapelerin aynı olmasına gerek yoktur)

a1 = np.array([[1,2],
               [2,0],
               [3,1]])

a2 = np.array ([[4,3],
                [1,2]])

print(np.dot(a1,a2))


[[ 6  7]
 [ 8  6]
 [13 11]]


## Reshape

In [311]:
m=np.arange(1,11)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [313]:
m.reshape(2,5) # 2*5 = 10 olduğundan ve 10=m olduğundan hatasız çalışır

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [315]:
m.reshape(3,5) #3*5= 15 olduğundan 15!= m olduğundan hata aldık.

ValueError: cannot reshape array of size 10 into shape (3,5)

In [317]:
# eleman sayısı ile reshape içindeki (satır * sütunun) aynısı olması gerekldiri reshape için
m.reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [319]:
n=np.arange(1,13)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [321]:
n.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [323]:
#otomatik olarak 4 kolonlu bir array yarattı
n.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [327]:
z=np.arange(50,100)
z

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [331]:
z.reshape(5,10)

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [333]:
z.reshape(-1,5)

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [721]:
f=np.arange(1,10)
f

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [725]:
f[np.newaxis, :] #yeni boyut ekledim öncesinde düz listeydi şimdi 10 sütun tek satırlı bi array oldu

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [727]:
f[np.newaxis, :].shape

(1, 9)

In [739]:
f[:, np.newaxis, np.newaxis]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])

In [747]:
f[:, np.newaxis, np.newaxis].shape

(9, 1, 1)

In [749]:
f[:, np.newaxis, np.newaxis].ndim

3

In [751]:
f[:, np.newaxis, None].ndim

3

In [761]:
y=f[None, :, None]
y.ndim

3

In [763]:
y

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]])

In [769]:
a=np.arange(1,7) 
x=a[np.newaxis,:]
x

array([[1, 2, 3, 4, 5, 6]])

In [773]:
x.shape

(1, 6)

# concatenate

In [335]:
x= np.array([1,2,3])
y= np.array([4,5,6])

In [337]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [339]:
l=[9,0]

In [341]:
np.concatenate([y,x,l])

array([4, 5, 6, 1, 2, 3, 9, 0])

In [359]:
a*2
b=a*2

In [353]:
# iki boyutlu

a= np.array([[1,2,3],[4,5,6],[7,8,10]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [373]:
c=np.concatenate([a,b])
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 20]])

In [363]:
a.ndim

2

In [365]:
a.shape

(3, 3)

In [369]:
c.ndim

2

In [371]:
c.shape

(6, 3)

In [375]:
#dimensionların aynı olması gerekir
m= np.concatenate([a,a])
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [377]:
#axis = 0 satır boyunca
m= np.concatenate([a,a],axis=0)
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [379]:
#axis= 1 sutun boyunca işlem
m= np.concatenate([a,a],axis=1 )
m

array([[ 1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4,  5,  6],
       [ 7,  8, 10,  7,  8, 10]])

In [385]:
d=np.concatenate([a,b], axis=1) #sütun sütun yani yan yana birleştiriyor
d

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8, 10, 14, 16, 20]])

# Splitting

In [387]:
l=[10,20,30,40,50,60,70,80] #list

In [389]:
l[0:5]

[10, 20, 30, 40, 50]

In [391]:
l[:5]

[10, 20, 30, 40, 50]

In [393]:
final=np.split(l, [2,5])
final

[array([10, 20]), array([30, 40, 50]), array([60, 70, 80])]

In [407]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
np.array_split(arr, 3) #array.split diyince random da bölüyor

[array([1, 2, 3]), array([4, 5]), array([6, 7])]

In [405]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
np.split(arr, 3) #sadece split yazınca eşit bölmeye çalışıyor

ValueError: array split does not result in an equal division

In [451]:
g=np.random.randint(10,100,(4,5))
g

array([[78, 33, 34, 39, 57],
       [77, 60, 62, 37, 44],
       [59, 86, 69, 31, 55],
       [23, 17, 16, 24, 21]])

In [455]:
# Split array 'g' into 3 sub-arrays along axis 1 (columns)
# This creates a list of arrays with:
# - First array: columns before index 1
# - Second array: columns from index 1 up to (but not including) index 3
# - Third array: columns from index 3 onwards
gfinal=np.split(g,[1, 3], axis=1)
gfinal

[array([[78],
        [77],
        [59],
        [23]]),
 array([[33, 34],
        [60, 62],
        [86, 69],
        [17, 16]]),
 array([[39, 57],
        [37, 44],
        [31, 55],
        [24, 21]])]

In [459]:
gfinall=np.split(g,[1,3], axis=0)
gfinall

[array([[78, 33, 34, 39, 57]]),
 array([[77, 60, 62, 37, 44],
        [59, 86, 69, 31, 55]]),
 array([[23, 17, 16, 24, 21]])]

In [463]:
gfinalll=np.split(g,[1], axis=0)
gfinalll

[array([[78, 33, 34, 39, 57]]),
 array([[77, 60, 62, 37, 44],
        [59, 86, 69, 31, 55],
        [23, 17, 16, 24, 21]])]

In [465]:
a=()

In [469]:
a,b,c=final
final

[array([10, 20]), array([30, 40, 50]), array([60, 70, 80])]

In [479]:
a,b,c=np.split(l,[2,5] )
a,b,c

(array([10, 20]), array([30, 40, 50]), array([60, 70, 80]))

In [481]:
a #orijinal arrayler etkilenmiyor

array([10, 20])

In [475]:
b

array([30, 40, 50])

In [477]:
c

array([60, 70, 80])

# Array elemanlarına erişmek

In [483]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [485]:
#birinci satır
a[0]

array([1, 2, 3, 4])

In [487]:
# ikinci satır
a[1]

array([5, 6, 7, 8])

In [489]:
#0.satır 0.kolon
a[0][0]

1

In [493]:
a[0,2]

3

In [495]:
#0.satır 1.kolon
a[0,1]

2

In [497]:
a[1,1]

6

In [499]:
#2.satır 2.kolon
a[2,2]

11

In [501]:
c= np.arange(1,17).reshape(2,8)
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [503]:
c[0,5]

6

In [509]:
c[1,2]=54 #indexteki değeri değiştirme

In [507]:
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 54, 12, 13, 14, 15, 16]])

In [511]:
c[:1]

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [515]:
c[0:2,5]

array([ 6, 14])

In [517]:
#2.satır 2.kolon 300 olarak değiştirildi
a[2,2]= 300
a

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10, 300,  12]])

In [527]:
zero=np.ones((5,5))
zero

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [531]:
zero[2,2]=54
zero

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1., 54.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [533]:
zero.reshape(1,25)

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., 54.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

### Slice indeksing

In [535]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [543]:
# 0 satırı ile 2. satır arasındaki satırları yazdı. (2.satır dahil değil)
a[0:2] #arada virgül olmadığı sürece satırdasın

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [539]:
a[:1]

array([[1, 2, 3, 4]])

In [547]:
a[:1,2]

array([3])

In [549]:
a[:] # bütün satır ve sütünu alır

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [551]:
c[:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 54, 12, 13, 14, 15, 16]])

In [553]:
#bütün satırları al ama 2.indexteki kolonu al yani bütün tabloyu alıp 2. index sütununu getir
a[:,2]

array([ 3,  7, 11])

In [555]:
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 54, 12, 13, 14, 15, 16]])

In [557]:
c[:,2]

array([ 3, 54])

In [559]:
#bütün satırları al ama 0'dan 2. kolona kadar olan sütünları al
a[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [561]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [573]:
c[:,1:4]

array([[ 2,  3,  4],
       [10, 54, 12]])

In [565]:
a[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [569]:
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 54, 12, 13, 14, 15, 16]])

In [571]:
c[0:2,1:4]

array([[ 2,  3,  4],
       [10, 54, 12]])

In [575]:
#bütün satırları ve bütün kolonlaru al
a[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [577]:
a[0:2,2]

array([3, 7])

# filter

In [579]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [581]:
a<7

array([ True,  True,  True,  True,  True,  True, False, False, False])

In [583]:
# 7 den küçük değerlere ulaştık
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [587]:
filt= a<5

In [589]:
a[filt]

array([1, 2, 3, 4])

In [591]:
#array tipinde and = &
filt= (a>5) & (a<9)

In [593]:
a[filt]

array([6, 7, 8])

In [595]:
#array tipinde or = |
filt= (a<5) | (a>8)

In [597]:
a[filt]

array([1, 2, 3, 4, 9])

In [599]:
#filtrenin değili (a<5 dışında kalanlar)
filt= ~(a<5)

In [601]:
a[filt]

array([5, 6, 7, 8, 9])

In [603]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [605]:
b<7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [607]:
#filtre boyutu bozar. istenirse sonra tekrardan boyut eklenebilir.
b[b<7]

array([1, 2, 3, 4, 5, 6])

In [609]:
b[b<7].reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [611]:
# 7 den küçük elanlar ile oluşturulan altküme bir array
x= b[b<7].reshape(2,3)

In [613]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [621]:
z=np.arange(10,20).reshape(2,5)
z

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [625]:
z<=15

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False]])

In [629]:
z[z<14].reshape(2,2)

array([[10, 11],
       [12, 13]])

# SUM

In [631]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [633]:
#bütün elemanları topluyor.
print(np.sum(b))

45


In [635]:
#7'den küçük olanların toplamı
np.sum(b[b<7])

21

In [637]:
# sütunların toplamı
np.sum(b,axis=0)

array([12, 15, 18])

In [639]:
# satırların toplamı
np.sum(b,axis=1)

array([ 6, 15, 24])

In [643]:
np.arange(13,1,-3)

array([13, 10,  7,  4])